name: Builds

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    tags:
    description: 'Test scenario tags'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install LLVM and Clang
        if: ${{ !(matrix.os == 'macos-latest') }} # macos fail on clang-actions (why?)
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "14.0"
      
      - name: Install CMake
        uses: lukka/get-cmake@latest

      - name: Compiling
        run: |
          cmake -DCMAKE_BUILD_TYPE=Release -S . -B build
          cmake --build build --config Release

      - name: Run
        run: ./siemens/bin/unittest