name: Builds

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install CMake
        uses: lukka/get-cmake@latest

      - name: Compiling
        run: |
          cmake -DCMAKE_BUILD_TYPE=Release -S . -B build
          cmake --build build --config Release

      - name: Run
        if: ${{ !(matrix.os == 'windows-latest') }}
        run: ./siemens/bin/unittest

      - name: RunWin
        if: ${{ (matrix.os == 'windows-latest') }}
        run: .\siemens\bin\unittest.exe